# Generated by Django 3.2.7 on 2021-09-22 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_project', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
